/**
 * Return remaining gas fees from a wallet to the master wallet
 * Usage: npx tsx scripts/return-gas-fees.ts <walletAddress>
 */

import { createWalletClient, createPublicClient, http, formatEther, parseEther } from "viem";
import { base } from "viem/chains";
import { privateKeyToAccount } from "viem/accounts";
import { BASE_RPC_URL } from "../lib/constants";
import { generateUserOfframpWallet, getMasterWallet } from "../lib/offramp-wallet";
import { supabaseAdmin } from "../lib/supabase";

const walletAddress = process.argv[2] || "0x20717a8732D3341201Fa33A06bBE5ed91DBfdEB2";

async function returnGasFees() {
  console.log(`\n💰 Returning Gas Fees`);
  console.log(`=====================\n`);
  console.log(`Wallet: ${walletAddress}\n`);

  try {
    // Find transaction to get user identifier
    const { data: transactions, error } = await supabaseAdmin
      .from("offramp_transactions")
      .select("*")
      .eq("unique_wallet_address", walletAddress.toLowerCase())
      .order("created_at", { ascending: false })
      .limit(1);

    if (error || !transactions || transactions.length === 0) {
      console.error(`❌ No transaction found for this wallet\n`);
      return;
    }

    const transaction = transactions[0];
    console.log(`✅ Found transaction: ${transaction.transaction_id}`);
    console.log(`   User: ${transaction.user_email}`);
    console.log(`   Status: ${transaction.status}\n`);

    // Get user identifier to generate wallet
    const userIdentifier = transaction.user_id || transaction.user_email || `guest_${transaction.user_account_number}`;
    const wallet = generateUserOfframpWallet(userIdentifier);

    // Verify wallet address matches
    if (wallet.address.toLowerCase() !== walletAddress.toLowerCase()) {
      console.error(`❌ Wallet address mismatch!`);
      console.error(`   Generated: ${wallet.address}`);
      console.error(`   Expected: ${walletAddress}\n`);
      console.log(`💡 This wallet might not be generated by our system, or the user identifier is incorrect.\n`);
      return;
    }

    console.log(`✅ Wallet verified as system-generated\n`);

    // Create clients
    const account = privateKeyToAccount(wallet.privateKey as `0x${string}`);
    const walletClient = createWalletClient({
      account,
      chain: base,
      transport: http(BASE_RPC_URL),
    });

    const publicClient = createPublicClient({
      chain: base,
      transport: http(BASE_RPC_URL),
    });

    // Check ETH balance
    const ethBalance = await publicClient.getBalance({
      address: wallet.address as `0x${string}`,
    });

    const balanceFormatted = formatEther(ethBalance);
    console.log(`📊 Current ETH Balance: ${balanceFormatted} ETH\n`);

    if (ethBalance === BigInt(0)) {
      console.log(`⚠️  No ETH to return\n`);
      return;
    }

    // Get master wallet
    const masterWallet = getMasterWallet();
    console.log(`📤 Master Wallet: ${masterWallet.address}\n`);

    // Calculate amount to send (leave 0.00001 ETH for safety)
    const minReserve = parseEther("0.00001");
    const ethToSend = ethBalance > minReserve ? ethBalance - minReserve : BigInt(0);

    if (ethToSend === BigInt(0)) {
      console.log(`⚠️  Balance too low to return (need at least 0.00001 ETH reserve)\n`);
      return;
    }

    console.log(`💸 Sending ${formatEther(ethToSend)} ETH to master wallet...\n`);

    // Send ETH
    const txHash = await walletClient.sendTransaction({
      to: masterWallet.address as `0x${string}`,
      value: ethToSend,
    });

    console.log(`⏳ Transaction sent: ${txHash}`);
    console.log(`   Waiting for confirmation...\n`);

    // Wait for confirmation
    const receipt = await publicClient.waitForTransactionReceipt({
      hash: txHash,
    });

    if (receipt.status === "success") {
      console.log(`✅ Gas fees returned successfully!\n`);
      console.log(`   Transaction: ${txHash}`);
      console.log(`   Amount: ${formatEther(ethToSend)} ETH`);
      console.log(`   Remaining: ${formatEther(minReserve)} ETH (reserve)\n`);
    } else {
      console.error(`❌ Transaction failed\n`);
    }
  } catch (error: any) {
    console.error(`❌ Error: ${error.message}\n`);
    if (error.stack) {
      console.error(`   ${error.stack}\n`);
    }
  }
}

returnGasFees();

